/**
 * Vertical Trope Master List. Sandboxed to Vertical mode only.
 *
 * Sourced directly from the user's "Vertical Tropes Master List" doc, with
 * tropes grouped into the 12 families described in the vertical workshop notes.
 */

import type { TropeTag, TropeFamilyId } from '@/types'

const t = (id: string, family: TropeFamilyId, label: string, description = ''): TropeTag => ({
  id,
  family,
  label,
  description,
})

export const VERTICAL_TROPES: Record<TropeFamilyId, TropeTag[]> = {
  relationship_core: [
    t('enemies_to_lovers', 'relationship_core', 'Enemies to lovers'),
    t('rivals_to_lovers', 'relationship_core', 'Rivals to lovers'),
    t('hate_first_sight', 'relationship_core', 'Hate at first sight'),
    t('contract_marriage', 'relationship_core', 'Contract marriage'),
    t('marriage_of_convenience', 'relationship_core', 'Marriage of convenience'),
    t('forced_marriage', 'relationship_core', 'Forced / arranged marriage'),
    t('flash_marriage', 'relationship_core', 'Flash marriage'),
    t('pregnancy_marriage', 'relationship_core', 'Pregnancy marriage'),
    t('divorce_day_reversal', 'relationship_core', 'Divorce-day reversal'),
    t('second_chance', 'relationship_core', 'Second chance romance'),
    t('friends_to_lovers', 'relationship_core', 'Friends to lovers'),
    t('one_night_to_soulmate', 'relationship_core', 'One night stand to soulmate'),
    t('fated_mates', 'relationship_core', 'Fated mates'),
    t('forbidden_romance', 'relationship_core', 'Forbidden romance'),
    t('age_gap', 'relationship_core', 'Age gap (older man, younger woman)'),
    t('taboo_coded', 'relationship_core', 'Taboo-coded romance'),
    t('he_falls_first', 'relationship_core', 'He falls first, she falls harder'),
    t('grumpy_sunshine', 'relationship_core', 'Grumpy / sunshine'),
    t('cold_ceo_warm_girl', 'relationship_core', 'Cold CEO, warm girl'),
    t('touch_her_and_die', 'relationship_core', 'Touch-her-and-die protector'),
    t('jealous_possessive_li', 'relationship_core', 'Jealous possessive LI'),
    t('love_triangle', 'relationship_core', 'Love triangle (two men, one woman)'),
    t('regret_too_late', 'relationship_core', '"All too late" regret romance'),
    t('be_my_girlfriend_for_a_week', 'relationship_core', 'Convenience dating ("be my girlfriend for a week")'),
    t('co_parenting_romance', 'relationship_core', 'Co-parenting romance'),
  ],
  identity_secret: [
    t('hidden_identity', 'identity_secret', 'Hidden identity'),
    t('mistaken_identity', 'identity_secret', 'Mistaken identity'),
    t('lost_heiress', 'identity_secret', 'Lost heiress / hidden heiress'),
    t('secret_billionaire', 'identity_secret', 'Secret billionaire / secret CEO'),
    t('secret_marriage', 'identity_secret', 'Secret marriage'),
    t('secret_engagement', 'identity_secret', 'Secret engagement'),
    t('undercover_maid', 'identity_secret', 'Undercover as a maid / assistant / bodyguard'),
    t('identity_theft_sister', 'identity_secret', 'Impostor sister steals her life'),
    t('secret_genius', 'identity_secret', 'Secret genius (doctor, hacker, chef, fighter)'),
    t('secret_inheritance', 'identity_secret', 'Secret inheritance / secret will'),
    t('secret_parentage', 'identity_secret', 'Secret parentage / swapped at birth'),
    t('selective_amnesia', 'identity_secret', 'Selective amnesia'),
    t('hidden_benefactor', 'identity_secret', 'Hidden benefactor'),
    t('rival_company_heir', 'identity_secret', 'He is the rival company\'s heir'),
  ],
  power_status_imbalance: [
    t('billionaire_romance', 'power_status_imbalance', 'Billionaire romance (CEO, tycoon, heir)'),
    t('mafia_boss', 'power_status_imbalance', 'Mafia boss romance'),
    t('royalty_prince', 'power_status_imbalance', 'Royalty / prince / noble heir'),
    t('celebrity_idol', 'power_status_imbalance', 'Celebrity / idol / famous athlete'),
    t('he_owns_the_building', 'power_status_imbalance', '"He owns the building"'),
    t('boss_assistant', 'power_status_imbalance', 'Boss / assistant'),
    t('poor_girl_bullied_elevated', 'power_status_imbalance', 'Poor girl bullied then elevated'),
    t('marry_to_save_family', 'power_status_imbalance', 'Marriage to save family'),
    t('he_sponsors_her', 'power_status_imbalance', '"He sponsors her" patron protector'),
    t('he_buys_the_company', 'power_status_imbalance', '"He buys the company"'),
    t('legal_power_fantasy', 'power_status_imbalance', '"He\'s the judge / lawyer"'),
  ],
  revenge_betrayal_humiliation: [
    t('betrayal_by_fiance', 'revenge_betrayal_humiliation', 'Betrayal by fiancé / husband'),
    t('sister_steals_fiance', 'revenge_betrayal_humiliation', 'Sister / cousin steals fiancé'),
    t('wedding_humiliation', 'revenge_betrayal_humiliation', 'Wedding / banquet humiliation'),
    t('face_slapping_revenge', 'revenge_betrayal_humiliation', '"Face-slapping" revenge'),
    t('revenge_marriage', 'revenge_betrayal_humiliation', 'Revenge marriage'),
    t('all_of_you_will_pay', 'revenge_betrayal_humiliation', '"All of you will pay" comeback'),
    t('public_exposure', 'revenge_betrayal_humiliation', 'Public exposure / boardroom reveal'),
    t('gaslighting_reversal', 'revenge_betrayal_humiliation', 'Gaslighting reversal'),
    t('bully_to_regret', 'revenge_betrayal_humiliation', 'Bully-to-regret'),
    t('false_accusation', 'revenge_betrayal_humiliation', 'False accusation then vindication'),
    t('kicked_out_pregnant', 'revenge_betrayal_humiliation', 'Kicked out while pregnant, triumphant return'),
    t('villain_loop_structure', 'revenge_betrayal_humiliation', 'Villain loop structure'),
  ],
  pregnancy_child: [
    t('secret_baby', 'pregnancy_child', 'Secret baby / hidden child'),
    t('whos_the_father', 'pregnancy_child', 'Who\'s the father? (paternity test cliffhanger)'),
    t('baby_contract', 'pregnancy_child', 'Baby contract'),
    t('mistaken_paternity', 'pregnancy_child', 'Mistaken paternity / switched embryos'),
    t('single_mom_billionaire', 'pregnancy_child', 'Single mom meets billionaire'),
    t('ceo_mother_grandchild', 'pregnancy_child', '"CEO\'s mother wants a grandchild"'),
    t('child_matchmaker', 'pregnancy_child', 'Child as matchmaker'),
    t('shes_carrying_the_heir', 'pregnancy_child', '"She\'s carrying the heir"'),
  ],
  family_inheritance: [
    t('evil_mother_in_law', 'family_inheritance', 'Evil mother-in-law'),
    t('family_steals_company', 'family_inheritance', 'Family steals her company'),
    t('inheritance_condition', 'family_inheritance', 'Inheritance condition'),
    t('will_reading_sabotage', 'family_inheritance', 'Will reading sabotage'),
    t('adopted_real_heiress', 'family_inheritance', 'Adopted daughter revealed as real heiress'),
    t('half_siblings_rivalry', 'family_inheritance', 'Half-siblings rivalry'),
    t('pampered_by_uncles', 'family_inheritance', 'Pampered by uncles'),
    t('reunion_lost_family', 'family_inheritance', 'Reunion / lost family found'),
    t('fake_vs_real_daughter', 'family_inheritance', 'Fake daughter vs real daughter'),
  ],
  forced_proximity: [
    t('locked_in_room', 'forced_proximity', 'Locked in a room'),
    t('same_bed', 'forced_proximity', 'Same bed trope'),
    t('fake_roommates', 'forced_proximity', 'Fake roommates'),
    t('forced_to_live_together', 'forced_proximity', 'Married and living together against their will'),
    t('share_hotel_room', 'forced_proximity', 'Share a hotel room'),
    t('work_trip', 'forced_proximity', 'Work trip / business travel'),
    t('small_circle_world', 'forced_proximity', 'Small circle world'),
  ],
  steam_heat: [
    t('edging_teasing', 'steam_heat', 'Edging-style teasing'),
    t('one_night_changes_everything', 'steam_heat', '"One night changes everything"'),
    t('jealous_interruption', 'steam_heat', 'Jealous interruption'),
    t('marking_possessive', 'steam_heat', '"Marking" / possessive gestures'),
    t('teach_me_seduction', 'steam_heat', '"Teach me" seduction training'),
    t('contract_intimacy_clauses', 'steam_heat', 'Contract intimacy clauses'),
  ],
  second_chance_time_bend: [
    t('rebirth_for_revenge', 'second_chance_time_bend', 'Rebirth / "reborn for revenge"'),
    t('glow_up_comeback', 'second_chance_time_bend', 'Return after betrayal, glow-up comeback'),
    t('amnesia_reset', 'second_chance_time_bend', 'Amnesia reset'),
    t('we_were_married_before', 'second_chance_time_bend', '"We were married before"'),
    t('he_wronged_her_before', 'second_chance_time_bend', '"He wronged her before"'),
  ],
  supernatural_romance: [
    t('werewolf_mate', 'supernatural_romance', 'Werewolf / fated mate / alpha king'),
    t('vampire_romance', 'supernatural_romance', 'Vampire romance'),
    t('ghost_romance', 'supernatural_romance', 'Ghost romance'),
    t('witch_curse', 'supernatural_romance', 'Witch / curse / soulmate bond'),
    t('myth_inspired', 'supernatural_romance', 'Myth-inspired romance'),
  ],
  mystery_danger: [
    t('marry_to_investigate', 'mystery_danger', '"Marry to investigate" suspect husband'),
    t('murder_mystery_inheritance', 'mystery_danger', 'Murder mystery tied to inheritance'),
    t('kidnap_bodyguard', 'mystery_danger', 'Kidnapping / bodyguard LI'),
    t('stalker_ex', 'mystery_danger', 'Stalker ex / protection romance'),
    t('dangerous_but_safe', 'mystery_danger', '"He\'s dangerous but safe with her"'),
    t('blackmail_marriage', 'mystery_danger', 'Blackmail marriage'),
  ],
  micro_tropes_per_episode: [
    t('accidental_reveal', 'micro_tropes_per_episode', 'Accidental reveal'),
    t('misunderstanding_spike', 'micro_tropes_per_episode', 'Misunderstanding spike to cliffhanger'),
    t('public_confront_private_tender', 'micro_tropes_per_episode', 'Public confrontation / private tenderness'),
    t('receipt_drop', 'micro_tropes_per_episode', 'Receipt drop (text screenshot, audio memo)'),
    t('walk_in_moment', 'micro_tropes_per_episode', 'Walk-in moment'),
    t('slap_splash_cake', 'micro_tropes_per_episode', 'Slap / splash / cake-to-face'),
    t('villain_smirk_panic_punish', 'micro_tropes_per_episode', 'Villain smirk → panic → punishment loop'),
  ],
}
