import type { CharacterId, ElementId } from './id'

/**
 * The atomic unit of screenplay content. Each element is one paragraph in
 * Final Draft's terminology. The editor is block-based: every paragraph has
 * a typed element. Tab/Enter route between types based on the routing table.
 */
export type ScreenplayElementType =
  | 'scene_heading'
  | 'action'
  | 'character'
  | 'dialogue'
  | 'parenthetical'
  | 'transition'
  | 'shot'
  | 'general'
  | 'lyric'
  | 'cast_list'      // multi-cam: list of characters in scene
  | 'sfx'            // multi-cam: SFX in bold
  | 'act_label'      // e.g., "ACT ONE", "END OF ACT ONE"
  | 'episode_label'  // vertical: "EPISODE 12"
  | 'centered_text'  // ">  TITLE  <" Fountain-style centered
  | 'page_break'
  | 'note'           // Fountain [[notes]] — non-printing

/** Character cue extensions: (V.O.), (O.S.), etc. */
export type CharacterExtension =
  | 'V.O.'
  | 'O.S.'
  | 'O.C.'
  | 'CONT\'D'
  | 'PRELAP'
  | 'FILTERED'
  | 'INTO PHONE'
  | 'OVER RADIO'
  | 'SUBTITLED'

/** Scene heading intro types. */
export type SceneIntro = 'INT.' | 'EXT.' | 'EST.' | 'INT./EXT.' | 'I/E.'

/** Single screenplay paragraph. */
export interface ScreenplayElement {
  id: ElementId
  type: ScreenplayElementType
  text: string

  // For character cues: the linked character id (for tracking, voice fingerprint).
  characterId?: CharacterId
  // For character cues: extension like (V.O.), (O.S.) — stored separately.
  extension?: CharacterExtension | null
  // For dual dialogue: id of paired character element (the ^).
  dualWith?: ElementId | null
  // For scene headings: parsed components.
  sceneIntro?: SceneIntro
  sceneLocation?: string
  sceneTime?: string
  // Scene number (for shooting scripts).
  sceneNumber?: string

  // Author intent: locked elements never get modified by AI/Modify.
  locked?: boolean

  // Revision tracking: which revision set introduced this paragraph.
  revisionSetId?: string

  // Inline notes attached to this paragraph (FD ScriptNotes equivalent).
  noteIds?: string[]

  // For Vertical episodes: the episode id this paragraph belongs to.
  episodeId?: string

  // For dialogue: alternate takes (FD Alt Dialogue).
  alts?: Array<{ id: string; text: string; label?: string; active?: boolean }>

  // Cached page number from last pagination. Updated by the pagination engine.
  pageHint?: number

  // Soft metadata for diagnostics: was this paragraph generated by the AI?
  aiGenerated?: boolean
  // Soft metadata: human-edited after AI generation?
  humanEdited?: boolean
}

/**
 * The screenplay document. An ordered list of elements plus settings.
 * Everything else (scene list, character list) is derived from this list.
 */
export interface ScreenplayDocument {
  elements: ScreenplayElement[]
  // Optional title page metadata (Fountain title-page fields).
  titlePage: {
    title?: string
    credit?: string
    author?: string
    source?: string
    draftDate?: string
    contact?: string
    notes?: string
    coverPage?: string
  }
}
