/**
 * Humanization rules. Applied globally across PageCraft, with relaxations only
 * inside Vertical-mode dialogue (where on-the-nose, declarative speech is the
 * craft target).
 *
 * Sourced from: the user's "Humanization Rules" doc, the Master Guide to
 * Screenwriting Craft, and accumulated red-flag patterns from professional
 * script readers.
 *
 * EM-DASH POLICY: zero tolerance. The em-dash character U+2014 is never
 * emitted by PageCraft. It is auto-converted to "--" (the screenplay
 * interruption convention) in dialogue, or to ", . ;" in prose.
 */

export const EM_DASH = '\u2014'
export const EN_DASH = '\u2013'

/** AI-tell phrases and corporate connectors that should not appear in output. */
export const BANNED_PHRASES: string[] = [
  // Self-referential AI
  'as an ai language model',
  'as an ai',
  'according to my training',
  'according to my programming',
  'based on my training',
  'based on my programming',
  'i am designed to',
  'this response was generated by',
  'i cannot experience emotions',
  "i don't have feelings",
  'i lack human understanding',
  "i'm unable to perform tasks outside my training",
  "from a machine learning perspective",
  "as inferred by",
  "from a computational standpoint",

  // Corporate stiffness
  'it is worth noting that',
  'it should be stated',
  'in conclusion',
  'to summarize',
  'however, it should be stated that',
  'moreover, the evidence suggests',
  'therefore, it can be deduced',
  'on the contrary',
  'this demonstrates that',
  'in many cases',
  'generally speaking',
  'to the best of my knowledge',
  'as far as i understand',
  'in most instances',
  'often, it is the case that',
  'it might be worth considering',

  // Algorithmic / data
  'the data suggests that',
  'statistically speaking',
  'according to probability',
  'the model predicts that',
  'using the training dataset',
  'this output is generated using',
  'from a probabilistic standpoint',

  // Empty hedging
  'it depends on the context',
  'there are many possibilities to consider',
  'both options have their merits',
  'this is a subjective matter',
  'while opinions may vary',

  // Robotic structural cliches
  'this is because',
  'the reason for this is',
  'the next step is',
  'this happens when',
  'the process involves',
  'in this case',
  'to elaborate further',

  // Overcompensating enthusiasm
  "that's such an amazing and incredible idea",
  'what a brilliant and perfect concept',
  'this is truly fascinating beyond words',
  'absolutely phenomenal',
]

/** Formal transitions to soften in screenplay prose and app text. */
export const BANNED_CONNECTORS: string[] = [
  'however',
  'moreover',
  'furthermore',
  'thus',
  'therefore',
  'consequently',
  'subsequently',
  'meanwhile',
  'additionally',
  'in addition',
  'in contrast',
  'on the other hand',
  'as a result',
]

/** Sentence-starter chains the linter watches for (3-in-a-row of the same opener). */
export const REPEATED_STARTERS: string[] = [
  'it is',
  'this is',
  'there are',
  'there is',
  'that is',
  'these are',
]

/** Action-line interiority leak patterns ("character feels X"). */
export const INTERIORITY_PATTERNS: RegExp[] = [
  /\b(feels|feeling|felt) (sad|happy|nervous|scared|terrified|anxious|excited|angry|devastated|ashamed|guilty|nostalgic|melancholy|relieved|exhausted|elated|jealous|in love|hopeful|hopeless|lonely|overwhelmed)\b/i,
  /\bis (sad|happy|nervous|scared|terrified|anxious|excited|angry|devastated|ashamed|guilty|relieved|elated|jealous|in love|hopeful|hopeless|lonely|overwhelmed)\b/i,
  /\bthinks (about|to himself|to herself|to themselves)\b/i,
  /\bremembers that\b/i,
  /\brealizes that\b/i,
  /\bunderstands that\b/i,
  /\bwonders if\b/i,
  /\bknows that\b/i,
  /\bdecides that\b/i,
]

/** Camera-direction tokens flagged as "writer dictating to director." */
export const CAMERA_DIRECTION_FLAGS: RegExp[] = [
  /\b(PAN (UP|DOWN|LEFT|RIGHT)|ZOOM (IN|OUT)|TRACKING SHOT|DOLLY|CRANE|TILT (UP|DOWN)|RACK FOCUS|WHIP PAN)\b/,
  /\bWE SEE\b/i, // gentle flag — common but tells, not shows
]

/** Overwriting flags (literary verbs, adjective stacks). */
export const OVERWRITING_VERBS: string[] = [
  'shimmers', 'glistens', 'cascades', 'undulates', 'gleams',
  'crystalizes', 'engulfs', 'permeates', 'envelopes', 'meanders',
  'saunters', 'sashays', 'glistening', 'shimmering',
]

/** Em-dash policy. */
export const EM_DASH_POLICY = {
  enabled: true,
  /** In dialogue, replace U+2014 with the FD double-hyphen convention. */
  replacementInDialogue: '--',
  /** In prose (action / centered / general), replace with a comma. The lint pass
   *  also evaluates context — a sentence-ending dash becomes a period. */
  replacementInProse: ',',
  /** En-dash policy: also converted to a single dash. */
  replaceEnDash: true,
} as const

/** Domain-specific dialogue lint that DOES NOT apply in Vertical mode. */
export const VERTICAL_EXEMPT_LINTS = new Set<string>([
  'on_the_nose',
  'declared_feeling',
  'theme_in_dialogue',
  'formal_connector_in_dialogue',
])
